name: Build Check

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main ]

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make docker-pull

  breaking-change:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: git
    run: |
      git tag
      git describe
      git tag --sort=committerdate | tail -1
    - name: Run make breaking-change with json output to annotate PR
      # Formats JSON output into Github workflow commands
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
      run: >
        BUF_FLAGS="--error-format json" make -s breaking-change
